# Generated by Django 4.1 on 2022-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
